# Generated by Django 3.2.19 on 2023-05-24 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessory',
            options={'verbose_name': 'Aksesuarlar', 'verbose_name_plural': '6. Aksesuarlar'},
        ),
        migrations.AlterModelOptions(
            name='computer',
            options={'verbose_name': 'Kompyuterlar', 'verbose_name_plural': '3. Komyuterlar'},
        ),
        migrations.AlterModelOptions(
            name='otherproducts',
            options={'verbose_name': 'Boshqa mahsulotlar', 'verbose_name_plural': '7. Boshqa mahsulotlar'},
        ),
        migrations.AlterModelOptions(
            name='smartphone',
            options={'verbose_name': 'SmartPhone', 'verbose_name_plural': '4. SmartPhone'},
        ),
        migrations.AlterModelOptions(
            name='smartwatch',
            options={'verbose_name': 'SmartWatch', 'verbose_name_plural': '5. SmartWatch'},
        ),
        migrations.AlterField(
            model_name='accessory',
            name='id',
            field=models.PositiveBigIntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='computer',
            name='id',
            field=models.PositiveBigIntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='firma',
            name='id',
            field=models.PositiveBigIntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='otherproducts',
            name='id',
            field=models.PositiveBigIntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='id',
            field=models.PositiveBigIntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='smartwatch',
            name='id',
            field=models.PositiveBigIntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
