# Generated by Django 3.2.19 on 2023-05-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_firma_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='address',
        ),
        migrations.AddField(
            model_name='users',
            name='address',
            field=models.CharField(default=None, max_length=500, verbose_name='Foydalanuvchi manzili'),
        ),
    ]
