# Generated by Django 3.2.19 on 2023-05-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20230524_0348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartwatch',
            name='prosessor',
        ),
        migrations.AddField(
            model_name='accessory',
            name='currency',
            field=models.CharField(choices=[('UZS', 'UZS'), ('RUB', 'RUB'), ('USD', 'USD')], default='UZS', max_length=3, verbose_name='Valyuta'),
        ),
        migrations.AddField(
            model_name='computer',
            name='currency',
            field=models.CharField(choices=[('UZS', 'UZS'), ('RUB', 'RUB'), ('USD', 'USD')], default='UZS', max_length=3, verbose_name='Valyuta'),
        ),
        migrations.AddField(
            model_name='otherproducts',
            name='currency',
            field=models.CharField(choices=[('UZS', 'UZS'), ('RUB', 'RUB'), ('USD', 'USD')], default='UZS', max_length=3, verbose_name='Valyuta'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='currency',
            field=models.CharField(choices=[('UZS', 'UZS'), ('RUB', 'RUB'), ('USD', 'USD')], default='UZS', max_length=3, verbose_name='Valyuta'),
        ),
        migrations.AddField(
            model_name='smartwatch',
            name='currency',
            field=models.CharField(choices=[('UZS', 'UZS'), ('RUB', 'RUB'), ('USD', 'USD')], default='UZS', max_length=3, verbose_name='Valyuta'),
        ),
    ]
